# Generated by Django 5.0.4 on 2024-11-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Name', max_length=50, verbose_name='Name')),
                ('anons', models.CharField(default='Anonse', max_length=250, verbose_name='Anonse')),
                ('full_text', models.TextField(verbose_name='Full text')),
                ('dete', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
    ]
