# Generated by Django 5.0.4 on 2024-11-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'News', 'verbose_name_plural': 'Newses'},
        ),
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.CharField(default='pythonlogo.webp', max_length=50, verbose_name='img'),
            preserve_default=False,
        ),
    ]
