# Generated by Django 5.0.4 on 2024-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_articles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(default='pythonlogo.svg', upload_to='cars'),
        ),
    ]
