# Generated by Django 5.0.4 on 2024-11-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.CharField(default='pythonlogo.svg', max_length=50, verbose_name='image'),
        ),
    ]
