# Generated by Django 5.0.4 on 2024-11-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_articles_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='img',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='pythonimage.webp', upload_to='images'),
        ),
    ]
