# Generated by Django 5.0.4 on 2024-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0007_alter_articles_anons_alter_articles_dete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='buyer_user_set', to='auth.group'),
        ),
    ]
