# Generated by Django 5.0.4 on 2024-11-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_buyer_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
